branch-defaults:
  default:
    environment: Screaperbackend-env
environment-defaults:
  Screaperbackend-env:
    branch: null
    repository: null
global:
  application_name: screaperbackend
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
